steps:
  # 1. Budowanie obrazu Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/kalkulator', '.']

  # 2. Przesłanie obrazu do Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/kalkulator']

  # 3. Wdrożenie na Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'kalkulator'
      - '--image'
      - 'gcr.io/$PROJECT_ID/kalkulator'
      - '--region'
      - 'europe-central2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8000'

images:
  - 'gcr.io/$PROJECT_ID/kalkulator'
